# -*- coding: utf-8 -*-
"""analyzer.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o8FTUJs2tN8fNDXzUqghofWbuVqt2sOr
"""

# 2. analyzer.py
code =
import pandas as pd
import re
from sklearn.feature_extraction.text import CountVectorizer
from wordcloud import WordCloud
import matplotlib.pyplot as plt

def preprocess_text(text):
    text = re.sub(r"[^ㄱ-ㅎ가-힣\s]", "", str(text))
    return text

def get_keywords(df, column='구성원 의견', stopwords=[]):
    texts = df[column].dropna().apply(preprocess_text)
    vectorizer = CountVectorizer(stop_words=stopwords)
    matrix = vectorizer.fit_transform(texts)
    keywords = vectorizer.get_feature_names_out()
    freq = matrix.sum(axis=0).A1
    return pd.DataFrame({'키워드': keywords, '빈도': freq}).sort_values(by='빈도', ascending=False)

def draw_wordcloud(df, title="워드클라우드"):
    word_freq = dict(zip(df['키워드'], df['빈도']))
    wc = WordCloud(font_path='/usr/share/fonts/truetype/nanum/NanumGothic.ttf',
                   background_color='white', width=800, height=400).generate_from_frequencies(word_freq)
    plt.figure(figsize=(10, 5))
    plt.imshow(wc, interpolation='bilinear')
    plt.axis('off')
    plt.title(title)
    plt.tight_layout()
    st.pyplot(plt)


with open("app.py", "w") as f:  # 또는 "analyzer.py"
    f.write(code)