# -*- coding: utf-8 -*-
"""analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pH-jhysT1tFxTcJA938ly7jAd67EC_46
"""

import pandas as pd
import re
from sklearn.feature_extraction.text import CountVectorizer
from wordcloud import WordCloud
import matplotlib.pyplot as plt

def preprocess_text(text):
    text = re.sub(r"[^ㄱ-ㅎ가-힣\s]", "", str(text))
    return text

def get_keywords(df, column='내용', stopwords=[]):
    texts = df[column].dropna().apply(preprocess_text)
    vectorizer = CountVectorizer(stop_words=stopwords)
    X = vectorizer.fit_transform(texts)
    keyword_freq = X.sum(axis=0).A1
    keywords = pd.DataFrame({'키워드': vectorizer.get_feature_names_out(), '빈도': keyword_freq})
    keywords = keywords.sort_values(by='빈도', ascending=False)
    return keywords

def draw_wordcloud(keywords, font_path=None):
    wordcloud = WordCloud(font_path=font_path, background_color='white', width=800, height=400)
    freqs = dict(zip(keywords['키워드'], keywords['빈도']))
    wordcloud.generate_from_frequencies(freqs)
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    plt.tight_layout()
    plt.show()