# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/183nTB9Erqy3RDT_MAEfxrSvXTo63axt9
"""

# 1. app.py
code =
import streamlit as st
import pandas as pd
from analyzer import get_keywords, draw_wordcloud

st.title("💬 면담 데이터 자동 분석기")

uploaded_file = st.file_uploader("📂 면담 데이터 Excel 파일 업로드", type=["xlsx"])

if uploaded_file is not None:
    df = pd.read_excel(uploaded_file)
    st.subheader("데이터 미리보기")
    st.dataframe(df.head())

    selected_col = st.selectbox("🔍 분석할 컬럼 선택", df.columns)

    if st.button("키워드 분석 시작"):
        keywords_df = get_keywords(df, column=selected_col)
        st.subheader("📊 주요 키워드")
        st.dataframe(keywords_df.head(20))
        st.subheader("☁️ 워드클라우드")
        draw_wordcloud(keywords_df, title=f"{selected_col} 키워드")

with open("app.py", "w") as f:  # 또는 "analyzer.py"
    f.write(code)